apiVersion: v1
kind: Service
metadata:
  labels:
    app: zabbix-postgres
    project: zabbix
  name: zabbix-postgres
spec:
  ports:
  - name: http
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: zabbix-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zabbix-postgres
    project: zabbix
  name: zabbix-postgres
spec:
  serviceName: zabbix-postgres
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres
  template:
    metadata:
      labels:
        app: zabbix-postgres
        project: zabbix
    spec:
      containers:
      - image: postgres:14
        name: postgres
        args:
          - "-c"
          - "max_connections=400"
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 8
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          timeoutSeconds: 1
        env:
          - name: POSTGRES_USER
            value: zabbix
          - name: POSTGRES_PASSWORD
            value: zabbix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
    project: zabbix
  name: adminer
  namespace: plataforma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        project: zabbix
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}