apiVersion: v1
kind: Service
metadata:
  labels:
    app: zabbix-server
    project: zabbix
  name: zabbix-server
spec:
  ports:
  - name: trapper
    port: 10051
    protocol: TCP
    targetPort: 10051
  selector:
    app: zabbix-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zabbix-server
    project: zabbix
  name: zabbix-server
spec:
  serviceName: zabbix-server
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
        project: zabbix
    spec:
      containers:
      - image: zabbix/zabbix-server-pgsql:ubuntu-6.4.12
        name: zabbix-server
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 10051
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 8
        livenessProbe:
          tcpSocket:
            port: 10051
          initialDelaySeconds: 60
          timeoutSeconds: 1
        env:
          - name: POSTGRES_USER
            value: zabbix
          - name: POSTGRES_PASSWORD
            value: zabbix
          - name: POSTGRES_DB
            value: zabbix
          - name: DB_SERVER_HOST
            value: zabbix-postgres
          - name: DB_SERVER_PORT
            value: "5432"