apiVersion: v1
kind: Service
metadata:
  labels:
    app: zabbix-web
    project: zabbix
  name: zabbix-web
spec:
  ports:
  - name: trapper
    port: 10051
    protocol: TCP
    targetPort: 10051
  selector:
    app: zabbix-web
---
apiVersion: v1
data:
  POSTGRES_USER: emFiYml4
  POSTGRES_PASSWORD: emFiYml4
kind: Secret
metadata:
  name: zabbix-web
  labels:
    project: zabbix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix-web
    project: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
        project: zabbix
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:6.4.12-ubuntu
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        readinessProbe:
          failureThreshold: 8
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1        
        env:
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"        
          - name: DB_SERVER_HOST
            value: "zabbix-postgres"
          - name: DB_SERVER_PORT
            value: "5432"
          - name: PHP_TZ
            value: "America/Sao_Paulo"
          - name: POSTGRES_DB
            value: "zabbix"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-web
                key: POSTGRES_PASSWORD
                optional: false
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-web
                key: POSTGRES_USER 
                optional: false
