version: "3.9"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
    condition: on-failure
  update_config:
    parallelism: 1
    delay: 10s

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4.12
    environment:
      DB_SERVER_HOST: zabbix_db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix  
    networks:
      - "monitoring-network"
    ports:
      - "10051:10051"
    deploy: *template-deploy
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4.12
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix_db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix    
    networks:
      - "monitoring-network"
    deploy: *template-deploy
    ports:
      - "8080:8080"

networks: 
  monitoring-network:
    external: true