version: "3.9"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
      condition: any
  update_config:
      parallelism: 1
      delay: 10s

services:
  zabbix_db:
    image: postgres:15
    networks:
      - "monitoring-network"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    deploy: *template-deploy
  adminer:
    image: adminer
    networks:
      - "monitoring-network"
    ports:
      - 8090:8080
    deploy: *template-deploy

networks:
  monitoring-network:
    external: True

volumes:
  postgres-data:
    external: true